### ISSUE TITLE
LOG_LEVEL

### ISSUE THREAD

**Issue by demacdonald** [vajahath/lme#11]
Would be nice if it respected an env var for what level to actually log....For example LOG_LEVEL=info would still log info level logs,  but not debug... But setting it to debug would show debug and info.

**Comment by demacdonald** [comment]
... Or make LME package a class we can instantiate with options,  one being log level :)

**Comment by demacdonald** [comment]
... Another option to pass in would be boolean for having a timestamp with the logs.

**Comment by demacdonald** [comment]
Anyways, let me know what you would like....I can do the dev work for it.

**Comment by vajahath** [comment]
@demacdonald Thanks. I can make you a collaborator to this repo with your permission.

And can you shed a little more clarity to your issue? I didn't get it.
Having timestamp is a great idea.
Instantiating `lme` with a bunch of options on every file gives more flexibility, but it may feel a little messy. Thats why we added an `lmeconfig.json` file at the app-root. But, that's just my raw, _un-processed_ thoughts. Please explain a little more..

**Comment by demacdonald** [comment]
Hmm...Typical in my application, I will leave different level logs, which each have their own purpose. Some will be to help trace what is happening in the system, those I might use `lme.i`, while other times I wiill leave debug logs and use `lme.t` or some loggers have explicit levels for debug.

A typical log level system goes similar to: (...this has made me notice we do not cover many of the typical log levels and that the lines should likely have the same levels)
trace
debug
info
warn
error

I use each of these levels explicitly for their own purposes. When I go into production however, I do not want to overwhelm the logs with debugging statements that I found helpful during development. But, I also do not want to have to go delete those useful log statements as I might find them useful in the future.

Often times we use run time evaluated variables such as ENV-vars to help decide what to filter out.
So if we set a log level to = "info" we will see logs for info and below. This means we will not see debug or trace logs cluttering our log files.

I imagine things like the config file to be great for static things, which timestamp may make sense having in there and color settings, but being able to decide what to log would be nice if its didn't have to be in a file.

Keep in mind, many production applications will simply have a "logging file" where they instantiate the logger and do a logger.export on it. So the code to instantiate the logger would unlikely be in every file.

For now though, you raise a good point. Maybe timestamp boolean goes in the config file and we do not need to support being instantiated, but simply listen to an environment variable LOG_LEVEL.

I wouldn't mind being a collaborator... I would still boucne ideas off you first to make sure my ideas are not crazy ;)

**Comment by vajahath** [comment]
Great thought with the env-var.
You are free to do the dev work and would be perfect if you can fix this. ( <_feeling guilty_ `:|`> and I will be busy until 19th Jan. So I may not be able to review your code until then. But still, let me know how can I help you.)
I'm very happy to add you as a collaborator.
Meanwhile, I can update the documentations for the recent changes we've done.
Yes, we'll make changes by opening issues, discussing on it and reviewing each other. Neither my ideas are perfect `;)`
You can either use new branch or the fork. Feel free to follow your momentum. We'll fix the consequences later. _(Please try to avoid any breaking changes from the last released version 1.3.2 at [npm](https://www.npmjs.com/package/lme). If they are necessary, let me know.)_

**Comment by demacdonald** [comment]
- [ ] Ensure log and line have same functions
- [ ] Add handling env-var to only log certain log levels.

**Comment by vajahath** [comment]
I noticed it. There are no options to change the colors of `lme.line` functions. But the package works just right with the available features. The multiple argument support _(thanks for #10)_ was a highly demanded feature.
So what I'm thinking is, we can release the v1.4 with all these completed features, and push the above mentioned issues for v1.5. If you are in development with some of them, please don't stop, take your time. We'll add it in 1.5. What do you think?

**Comment by demacdonald** [comment]
Sure, works for me. I don't mind how you release this stuff to be honest :), I havn't used this package personally yet, still want to add a few more features until I think it is ready for me.

I put up an initial draft of this in a PR... would like some opinions thrown into it before I continue on it.

**Comment by demacdonald** [comment]
Also note...you should be able to change the color of the lines...they use the same config as the logs themselves...would make sense you want you error lines to be the same color as your error logs for readability.

**Comment by vajahath** [comment]
I've opened #15 to discuss about the line color functionality.
And I'll handle your PR shortly.

**Comment by demacdonald** [comment]
Update on this incase you did not notice: I closed my PR and my code cleanup. I merged everything into your experimental branch and leaving it up to you to merge when you are happy with it :)

**Comment by vajahath** [comment]
I'll definitely be handling this. I can't look at it at the moment since I'm entering into a new job. And thank you for your patience. :smile:

**Comment by vajahath** [comment]
Fixed by #23
