### ISSUE TITLE
include .npmignore file

### ISSUE THREAD

**Issue by vajahath** [vajahath/lme#6]
We don't have to push `./media` file to npm. right?

**Comment by demacdonald** [comment]
Correct. You do not need to include anything that is not required for the package to run.

Certain files are excluded by default (ie: .npmrc, .git, etc) and some are included automatically (ie:readme, license, etc).

https://docs.npmjs.com/misc/developers

**Comment by demacdonald** [comment]
An alternative to it is:
https://docs.npmjs.com/files/package.json#files

Think of .npmrc as a blacklisting of the files to exclude...
We can work in the opposite direction and simply make a whitelist of files to include.

**Comment by vajahath** [comment]
Fixed. Thanks `:)` ( #8  )
