### ISSUE TITLE
Pass more than one item to methods

### ISSUE THREAD

**Issue by baldmountain** [vajahath/lme#9]
It would be nice to be able to call the methods with more than one item.

```javascript
let lme = require('lme');

lme.i(1, 2);
```

only prints

```
1
```

It would be nice if it printed

```
1 2
```

or

```
1
2
```

**Comment by demacdonald** [comment]
I can take a stab at this tomorrow if vajahath doesn't beat me to it :)

**Comment by vajahath** [comment]
@demacdonald haha it happens.
I'm in a journey too. So I may not be able to handle codes for the next 2 days. But trust me, I'll handle your requests.

@baldmountain thanks for pointing out that. We'll handle it shortly :)

**Comment by baldmountain** [comment]
I felt a little guilty. I haven't looked, but I don't think it will be a big change and normally I'd provide a pull request but I was lazy. :(

Thanks for looking at this so quickly. 👍

**Comment by demacdonald** [comment]
Haha,  no problem. Was very easy and fun... Review is the slowest part of getting in the change.

**Comment by vajahath** [comment]
Fixed by #10 
Thanks @demacdonald @baldmountain.
The fact is that I'm feeling guilty. Sorry for the delay. _[I was in a journey]_
Now this package is in 1.4.0-beta. Will be released shortly after testing.
